apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: package.github.io
build:
  tagPolicy:
    sha256: {}
  local:
    useBuildkit: true
    push: false
    useDockerCLI: false
  artifacts:
  - image: caddy

test:
  - image: caddy
    structureTests: [structure-test.yaml]
